
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://aayira9igsl97b.c8nbcjdtf2k8.eu-central-1.rds.amazonaws.com/innodb

    username: root
    password: nurhusein

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 5005